### ISSUE TITLE
TWE website no longer shows code blocks

### ISSUE THREAD

**Issue by tvld** [mdbootstrap/TW-Elements#1082]
As of today, none of the elements show code on the website, see for example the [button](https://tailwind-elements.com/docs/standard/components/buttons/) and click on ``<> show code``. 

It will show for one second and then disappear. Tested on Firefox 106, Ubuntu. The issue seems:

```scss
.collapse {
  visibility: collapse;
}
```
